default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 
  password: 

development:
  <<: *default
  database: myclass_dev

test:
  <<: *default
  database: myclass_test

production:
  <<: *default
  database: myclass_prod
